# Compile Vulkan GLSL shaders to SPIR-V and bake them into a header that
# RenderDeviceVulkan.cpp can `#include`. Run via `tools/compile_shaders.bat`
# from the repo root (or invoke this script directly with `pwsh -File ...`).

[CmdletBinding()]
param(
    [string]$RepoRoot = '',
    [string]$Compiler = 'glslangValidator'
)

$ErrorActionPreference = 'Stop'

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
if ([string]::IsNullOrEmpty($RepoRoot)) {
    $RepoRoot = (Resolve-Path (Join-Path $scriptDir '..')).Path
}

$shadersDir = Join-Path $RepoRoot 'shaders/vulkan'
$buildDir   = Join-Path $shadersDir 'build'
$outHeader  = Join-Path $RepoRoot 'src/platform/vulkan/ZCVulkanMinimalSpv.inl'

# Each entry: GLSL source file -> exported C++ array name.
$targets = @(
    [pscustomobject]@{ Source = 'sprite.vert'; Symbol = 'kVulkanMinimalVertSpv' },
    [pscustomobject]@{ Source = 'sprite.frag'; Symbol = 'kVulkanMinimalFragSpv' }
)

if (-not (Get-Command $Compiler -ErrorAction SilentlyContinue)) {
    throw "glslangValidator not found in PATH (looked for '$Compiler'). Install the Vulkan SDK or pass -Compiler <path>."
}

if (-not (Test-Path $buildDir)) {
    New-Item -ItemType Directory -Path $buildDir -Force | Out-Null
}

function Convert-SpvToWords {
    param([string]$Path, [string]$Symbol)

    $bytes = [System.IO.File]::ReadAllBytes($Path)
    if ($bytes.Length -eq 0 -or ($bytes.Length % 4) -ne 0) {
        throw "SPIR-V file '$Path' is empty or not a multiple of 4 bytes (size=$($bytes.Length))."
    }

    $wordCount = $bytes.Length / 4
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine("static const uint32_t ${Symbol}[] = {")
    [void]$sb.Append('    ')

    for ($i = 0; $i -lt $wordCount; $i++) {
        $word = [System.BitConverter]::ToUInt32($bytes, $i * 4)
        [void]$sb.AppendFormat('0x{0:x8}', $word)
        $isLast = ($i -eq ($wordCount - 1))
        if (-not $isLast) {
            [void]$sb.Append(', ')
        }
        # 8 words per row keeps the file diff-friendly.
        if (($i % 8) -eq 7 -and -not $isLast) {
            [void]$sb.AppendLine()
            [void]$sb.Append('    ')
        }
    }
    [void]$sb.AppendLine()
    [void]$sb.AppendLine('};')
    return $sb.ToString()
}

$header = [System.Text.StringBuilder]::new()
[void]$header.AppendLine('// AUTO-GENERATED by tools/compile_shaders.ps1 -- do not edit by hand.')
[void]$header.AppendLine('// Regenerate with: tools\compile_shaders.bat')
[void]$header.AppendLine('#include <stdint.h>')
[void]$header.AppendLine()

foreach ($t in $targets) {
    $src = Join-Path $shadersDir $t.Source
    $spv = Join-Path $buildDir ($t.Source + '.spv')
    if (-not (Test-Path $src)) {
        throw "Missing shader source: $src"
    }

    Write-Host "[shader] $($t.Source) -> $($t.Source).spv"
    & $Compiler -V $src -o $spv
    if ($LASTEXITCODE -ne 0) {
        throw "glslangValidator failed for $src (exit $LASTEXITCODE)."
    }

    [void]$header.AppendLine("// Source: shaders/vulkan/$($t.Source)")
    [void]$header.AppendLine((Convert-SpvToWords -Path $spv -Symbol $t.Symbol))
}

[System.IO.File]::WriteAllText($outHeader, $header.ToString())
Write-Host "[shader] Wrote $outHeader"
